apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"simpleapp"},"name":"simpleapp","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"simpleapp"}},"strategy":{},"template":{"metadata":{"labels":{"app":"simpleapp"}},"spec":{"containers":[{"image":"dgkanatsios/simpleapp","name":"simpleapp","resources":{}}]}}}}
  creationTimestamp: "2020-09-08T13:01:32Z"
  generation: 1
  labels:
    app: simpleapp
  name: simpleapp
  namespace: default
  resourceVersion: "79247"
  selfLink: /apis/apps/v1/namespaces/default/deployments/simpleapp
  uid: 20453622-a62a-4572-8745-e3abc76363c3
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: simpleapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simpleapp
    spec:
      containers:
      - image: dgkanatsios/simpleapp
        imagePullPolicy: Always
        name: simpleapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-09-08T13:01:39Z"
    lastUpdateTime: "2020-09-08T13:01:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-08T13:01:32Z"
    lastUpdateTime: "2020-09-08T13:01:39Z"
    message: ReplicaSet "simpleapp-857d747cf5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
