apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simpleapp
  name: simpleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleapp
  strategy: {}
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - image: dgkanatsios/simpleapp
        name: simpleapp
        resources: {}
