apiVersion: v1
kind: Service
metadata:
  name: elb-service
  labels:
    app: simpleapp
spec:
  type: LoadBalancer
  selector:
    app: simpleapp
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
